[REFACTOR] ASTextField RxCocoa 의존성 제거
ASAP-Side/iOS-aljo pull request #75
Opened 2024-03-13 11:38 UTC by lxodud

## 개요
ASTextField 객체 내부 RxCocoa 의존성을 제거했습니다.

Resolves: #72 

## PR 유형
어떤 변경 사항이 있나요?

- [ ] 새로운 기능 추가
- [ ] 버그 수정
- [ ] CSS 등 사용자 UI 디자인 변경
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [x] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [ ] 테스트 추가, 테스트 리팩토링
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [ ] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제

## PR Checklist
PR이 다음 요구 사항을 충족하는지 확인하세요.

- [x] 커밋 메시지 컨벤션에 맞게 작성했습니다.  Commit message convention 참고  (Ctrl + 클릭하세요.) 
- [x] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).

2024-03-14 07:05 UTC, leegyoungmin requested changes
바인딩 관련 메서드를 잘 제거해주셨네요!! Delegate 패턴을 잘 활용해주셨는데, 버그 발생한 부분이 있어서 코멘트 남겼습니다. 확인 부탁드립니다.

2024-03-14 07:05 UTC, leegyoungmin commented on aljo/Projects/UserInterface/ASAPKit/Sources/Components/ASTextField/ASUnderBarTextField.swift
> +    return false
LGTM!! 너무 좋은 방법 같습니다. 해당 부분을 TextView에도 동일하게 작성했는데, 3개의 자모가 나오는 경우에서 겹받침(ㄹㄱ, ㄹㅂ 등) 에 대한 버그가 있는 것 같습니다. 함께 논의해보면 좋을 것 같습니다.

2024-03-14 07:05 UTC, leegyoungmin commented on aljo/Projects/UserInterface/ASAPKit/Sources/Components/ASTextField/ASUnderBarTextField.swift
> +  }
UIAction을 활용하는 것은 어떨까요? objc를 활용하지 않고 Swift에서 동일하게 동작 시킬 수 있습니다.

2024-03-14 07:05 UTC, leegyoungmin commented on aljo/Projects/UserInterface/ASAPKit/Sources/Components/ASTextField/ASBorderHighlightTextField.swift
>      layer.cornerRadius = 6
UI 관련된 구성은 `configureUI` 라는 메서드로 하나로 감싸는 것은 어떨까요?

2024-03-14 10:56 UTC, lxodud commented on aljo/Projects/UserInterface/ASAPKit/Sources/Components/ASTextField/ASBorderHighlightTextField.swift
>      layer.cornerRadius = 6
수정완료했습니다!!
[ab11f8f](https://github.com/ASAP-Side/iOS-aljo/pull/75/commits/ab11f8f1f60ee85b154d8a66e9faaec4996d56be)

2024-03-14 10:57 UTC, lxodud commented on aljo/Projects/UserInterface/ASAPKit/Sources/Components/ASTextField/ASUnderBarTextField.swift
> +  }
수정 완료했습니다!!
[5202077](https://github.com/ASAP-Side/iOS-aljo/pull/75/commits/5202077080e35aa7c012f784bfcf2850e8e49479)

2024-03-15 07:14 UTC, leegyoungmin approved these changes
고생하셨습니당!

2024-03-15 07:26 UTC, merged